# ------------------------------------------------------------------------------------------------ #
#                                                                                                  #
#                         B o o k P a r a m e t e r s . p r o p e r t i e s                        #
#                                                                                                  #
# ------------------------------------------------------------------------------------------------ #

# This file gathers resources to be injected in the BookParameters class
#
# This is the generic version

# Title pattern when a book is provided
bookTitlePattern = {0} book parameters

# Title when no book is provided
defaultTitle = Default parameters

defaultTab.text = Default
defaultTab.toolTipText = Default settings

bookTab.toolTipText = Book settings

sheetTab.toolTipText = Settings for sheet {0}

sheetInitialChar = S

# Topics

General.text        = General
Languages.text      = OCR languages
Binarization.text   = Binarization
Scaling.text        = Scaling specifications
Staves.text         = Staves
Items.text          = Items
Processing.text     = Processing switches

# Music

MusicPane.text              = Music font
MusicPane.toolTipText       = Selection of music font
MusicPane.combo.toolTipText = Specific music font

# Text

TextPane.text               = Text font
TextPane.toolTipText        = Selection of text font
TextPane.combo.toolTipText  = Specific text font

# Quality

QualityPane.text                = Input quality
QualityPane.toolTipText         = Selection of input image quality
QualityPane.combo.toolTipText   = Specific input quality

# Lang

LangPane.text                   = OCR language(s)
LangPane.toolTipText            = Selection of main OCR language(s)
LangPane.langList.toolTipText   = Dominant languages for textual items
LangPane.langSpec.toolTipText   = Resulting specification

# FilterPane

FilterPane.text                         = Filter
FilterPane.kindLabel.text               = Kind
FilterPane.kindCombo.toolTipText        = Specific filter on image pixels

FilterPane.kindCombo.GLOBAL.toolTipText     = Apply the same threshold on every pixel
FilterPane.kindCombo.ADAPTIVE.toolTipText   = Apply a local threshold based on pixel neighbors

FilterPane.globalData.text              = Threshold
FilterPane.globalData.toolTipText       = Global threshold for foreground pixels

FilterPane.localDataMean.text           = Coeff for Mean
FilterPane.localDataMean.toolTipText    = Coefficient for mean pixel value

FilterPane.localDataDev.text            = Coeff for StdDev
FilterPane.localDataDev.toolTipText     = Coefficient for standard deviation

# Interline

InterlinePane.text          = Interline
InterlinePane.toolTipText   = <html>Specification of interline value, in pixels. \
                   <br>Use value 0 to disable and let the SCALE step retrieve interline value</html>

# Barline

BarlinePane.text                            =  Barline height
BarlinePane.toolTipText                     = Specification of barline height for 1-line staves
BarlinePane.combo.toolTipText               = Specific barline height, specified as a number of interlines

BarlinePane.combo.four.toolTipText          =   <html>Always 4 interlines</html>
BarlinePane.combo.twoThenFour.toolTipText   =   <html>2 interlines initially, then 4 interlines\
                                                <br>(applies only to 1-line staves)</html>
BarlinePane.combo.two.toolTipText           =   <html>Always 2 interlines\
                                                <br>(applies only to 1-line staves)</html>
BarlinePane.combo.oneThenTwo.toolTipText    =   <html>1 interline initially, then 2 interlines\
                                                <br>(applies only to 1-line staves)</html>

# Beam

BeamPane.text           = Beam thickness
BeamPane.toolTipText    = <html>Specification of beam thickness, in pixels. \
                    <br>Use value 0 to disable and let the SCALE step retrieve beam thickness</html>
